//! The scene description language: text → [`Scene`] and back (FR-4.1, FR-4.3, FR-4.7).
//!
//! A small, strictly declarative, KDL-style grammar (chosen in
//! docs/research/03-scene-formats-dsl.md): nodes have a name, an optional
//! `"label"`, `key=value` properties, and an optional `{ children }` block;
//! `//` and `/* */` comments are ignored. No loops or expressions — programmatic
//! scenes are generated by emitting this text.
//!
//! ```text
//! scene {
//!     background color=(0.05 0.05 0.08)
//!     material "red" base-color=(0.8 0.1 0.1)
//!     camera position=(3 2 5) look-at=(0 0 0) fov=50
//!     light direction=(-1 -2 -1) intensity=1.2 ambient=0.2
//!     sphere "ball" translate=(0 1 0) material="red"
//!     plane translate=(0 0 0) scale=(8 1 8)
//! }
//! ```

use crate::color::Rgb;
use crate::math::Vec3;
use crate::scene::{Geometry, Node, Scene, SceneCamera, SceneLight, Transform};

/// A parse or build error, with the 1-based source line for diagnostics (FR-4.1).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DslError {
    pub line: usize,
    pub message: String,
}

impl std::fmt::Display for DslError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "scene error at line {}: {}", self.line, self.message)
    }
}

impl std::error::Error for DslError {}

fn err<T>(line: usize, message: impl Into<String>) -> Result<T, DslError> {
    Err(DslError {
        line,
        message: message.into(),
    })
}

/// Parse DSL source into a [`Scene`] (FR-4.1, FR-4.3).
pub fn parse(source: &str) -> Result<Scene, DslError> {
    let tokens = tokenize(source)?;
    let mut parser = Parser { tokens, pos: 0 };
    let nodes = parser.parse_nodes(true)?;
    build_scene(nodes)
}

// ---------------------------------------------------------------------------
// Tokenizer
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq)]
enum Tok {
    Ident(String),
    Str(String),
    Num(f32),
    Eq,
    LParen,
    RParen,
    LBrace,
    RBrace,
    /// Node terminator: newline or `;`.
    Sep,
}

#[derive(Debug, Clone)]
struct Token {
    tok: Tok,
    line: usize,
}

fn tokenize(source: &str) -> Result<Vec<Token>, DslError> {
    let bytes = source.as_bytes();
    let mut i = 0;
    let mut line = 1;
    let mut out = Vec::new();
    while i < bytes.len() {
        let c = bytes[i] as char;
        match c {
            '\n' => {
                out.push(Token {
                    tok: Tok::Sep,
                    line,
                });
                line += 1;
                i += 1;
            }
            ';' => {
                out.push(Token {
                    tok: Tok::Sep,
                    line,
                });
                i += 1;
            }
            ' ' | '\t' | '\r' => i += 1,
            '/' if bytes.get(i + 1) == Some(&b'/') => {
                while i < bytes.len() && bytes[i] != b'\n' {
                    i += 1;
                }
            }
            '/' if bytes.get(i + 1) == Some(&b'*') => {
                i += 2;
                while i + 1 < bytes.len() && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                    if bytes[i] == b'\n' {
                        line += 1;
                    }
                    i += 1;
                }
                i += 2; // consume */
            }
            '=' => {
                out.push(Token { tok: Tok::Eq, line });
                i += 1;
            }
            '(' => {
                out.push(Token {
                    tok: Tok::LParen,
                    line,
                });
                i += 1;
            }
            ')' => {
                out.push(Token {
                    tok: Tok::RParen,
                    line,
                });
                i += 1;
            }
            '{' => {
                out.push(Token {
                    tok: Tok::LBrace,
                    line,
                });
                i += 1;
            }
            '}' => {
                out.push(Token {
                    tok: Tok::RBrace,
                    line,
                });
                i += 1;
            }
            '"' => {
                let (s, next) = lex_string(bytes, i + 1, line)?;
                out.push(Token {
                    tok: Tok::Str(s),
                    line,
                });
                i = next;
            }
            c if c == '-' || c == '+' || c == '.' || c.is_ascii_digit() => {
                let (n, next) = lex_number(bytes, i, line)?;
                out.push(Token {
                    tok: Tok::Num(n),
                    line,
                });
                i = next;
            }
            c if is_ident_start(c) => {
                let start = i;
                while i < bytes.len() && is_ident_char(bytes[i] as char) {
                    i += 1;
                }
                let word = std::str::from_utf8(&bytes[start..i]).unwrap().to_string();
                out.push(Token {
                    tok: Tok::Ident(word),
                    line,
                });
            }
            other => return err(line, format!("unexpected character '{other}'")),
        }
    }
    out.push(Token {
        tok: Tok::Sep,
        line,
    }); // ensure a trailing terminator
    Ok(out)
}

fn lex_string(bytes: &[u8], mut i: usize, line: usize) -> Result<(String, usize), DslError> {
    let mut s = String::new();
    while i < bytes.len() {
        match bytes[i] {
            b'"' => return Ok((s, i + 1)),
            b'\\' if i + 1 < bytes.len() => {
                let esc = bytes[i + 1];
                s.push(match esc {
                    b'n' => '\n',
                    b't' => '\t',
                    b'"' => '"',
                    b'\\' => '\\',
                    other => return err(line, format!("invalid escape '\\{}'", other as char)),
                });
                i += 2;
            }
            b'\n' => return err(line, "unterminated string"),
            b => {
                s.push(b as char);
                i += 1;
            }
        }
    }
    err(line, "unterminated string")
}

fn lex_number(bytes: &[u8], start: usize, line: usize) -> Result<(f32, usize), DslError> {
    let mut i = start;
    while i < bytes.len() {
        let c = bytes[i] as char;
        if c.is_ascii_digit() || matches!(c, '-' | '+' | '.' | 'e' | 'E') {
            i += 1;
        } else {
            break;
        }
    }
    let lexeme = std::str::from_utf8(&bytes[start..i]).unwrap();
    lexeme.parse::<f32>().map(|n| (n, i)).map_err(|_| DslError {
        line,
        message: format!("invalid number '{lexeme}'"),
    })
}

fn is_ident_start(c: char) -> bool {
    c.is_ascii_alphabetic() || c == '_'
}

fn is_ident_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || c == '_' || c == '-'
}

// ---------------------------------------------------------------------------
// Parser → raw nodes
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq)]
enum Value {
    Num(f32),
    Str(String),
    Vec3([f32; 3]),
}

#[derive(Debug, Clone)]
struct RawNode {
    name: String,
    line: usize,
    args: Vec<Value>,
    props: Vec<(String, Value)>,
    children: Vec<RawNode>,
}

struct Parser {
    tokens: Vec<Token>,
    pos: usize,
}

impl Parser {
    fn peek(&self) -> &Tok {
        &self.tokens[self.pos.min(self.tokens.len() - 1)].tok
    }

    fn line(&self) -> usize {
        self.tokens[self.pos.min(self.tokens.len() - 1)].line
    }

    fn at_end(&self) -> bool {
        self.pos >= self.tokens.len()
    }

    fn parse_nodes(&mut self, top_level: bool) -> Result<Vec<RawNode>, DslError> {
        let mut nodes = Vec::new();
        loop {
            // Skip blank separators. Guard on `at_end` so the clamped trailing
            // `Sep` token can't spin this loop forever.
            while !self.at_end() && matches!(self.peek(), Tok::Sep) {
                self.pos += 1;
            }
            if self.at_end() || self.pos == self.tokens.len() - 1 {
                return Ok(nodes);
            }
            if matches!(self.peek(), Tok::RBrace) {
                if top_level {
                    return err(self.line(), "unexpected '}'");
                }
                return Ok(nodes);
            }
            nodes.push(self.parse_node()?);
        }
    }

    fn parse_node(&mut self) -> Result<RawNode, DslError> {
        let line = self.line();
        let name = match self.peek().clone() {
            Tok::Ident(name) => {
                self.pos += 1;
                name
            }
            other => {
                return err(
                    line,
                    format!("expected a node name, found {}", describe(&other)),
                );
            }
        };
        let mut node = RawNode {
            name,
            line,
            args: Vec::new(),
            props: Vec::new(),
            children: Vec::new(),
        };

        loop {
            match self.peek().clone() {
                Tok::Sep => {
                    self.pos += 1;
                    break;
                }
                Tok::RBrace => break,
                Tok::LBrace => {
                    self.pos += 1;
                    node.children = self.parse_nodes(false)?;
                    self.expect(Tok::RBrace)?;
                    break;
                }
                Tok::Ident(key) if matches!(self.peek_at(1), Tok::Eq) => {
                    self.pos += 2; // ident '='
                    let value = self.parse_value()?;
                    node.props.push((key, value));
                }
                _ => node.args.push(self.parse_value()?),
            }
        }
        Ok(node)
    }

    fn peek_at(&self, ahead: usize) -> &Tok {
        &self.tokens[(self.pos + ahead).min(self.tokens.len() - 1)].tok
    }

    fn parse_value(&mut self) -> Result<Value, DslError> {
        let line = self.line();
        match self.peek().clone() {
            Tok::Num(n) => {
                self.pos += 1;
                Ok(Value::Num(n))
            }
            Tok::Str(s) => {
                self.pos += 1;
                Ok(Value::Str(s))
            }
            Tok::Ident(word) => {
                // Bareword: treated as a string value (e.g. type=directional).
                self.pos += 1;
                Ok(Value::Str(word))
            }
            Tok::LParen => {
                self.pos += 1;
                let mut comps = [0.0f32; 3];
                for slot in &mut comps {
                    match self.peek().clone() {
                        Tok::Num(n) => {
                            self.pos += 1;
                            *slot = n;
                        }
                        other => {
                            return err(
                                line,
                                format!("expected number in vector, found {}", describe(&other)),
                            );
                        }
                    }
                }
                self.expect(Tok::RParen)?;
                Ok(Value::Vec3(comps))
            }
            other => err(
                line,
                format!("expected a value, found {}", describe(&other)),
            ),
        }
    }

    fn expect(&mut self, want: Tok) -> Result<(), DslError> {
        if std::mem::discriminant(self.peek()) == std::mem::discriminant(&want) {
            self.pos += 1;
            Ok(())
        } else {
            let line = self.line();
            let found = describe(self.peek());
            err(line, format!("expected {}, found {found}", describe(&want)))
        }
    }
}

fn describe(tok: &Tok) -> String {
    match tok {
        Tok::Ident(s) => format!("'{s}'"),
        Tok::Str(_) => "a string".into(),
        Tok::Num(_) => "a number".into(),
        Tok::Eq => "'='".into(),
        Tok::LParen => "'('".into(),
        Tok::RParen => "')'".into(),
        Tok::LBrace => "'{'".into(),
        Tok::RBrace => "'}'".into(),
        Tok::Sep => "end of line".into(),
    }
}

// ---------------------------------------------------------------------------
// Serializer: Scene → DSL text (FR-4.7, round-trippable)
// ---------------------------------------------------------------------------

/// Serialize a [`Scene`] back to DSL text. `parse(&serialize(s))` reconstructs
/// an equal `Scene` (FR-4.7).
pub fn serialize(scene: &Scene) -> String {
    let mut out = String::from("scene {\n");
    out.push_str(&format!(
        "    background color={}\n",
        fmt_color(scene.background)
    ));
    if let Some(c) = scene.camera {
        out.push_str(&format!(
            "    camera position={} look-at={} fov={}\n",
            fmt_vec(c.position),
            fmt_vec(c.look_at),
            fmt_num(c.fov_deg),
        ));
    }
    out.push_str(&format!(
        "    light direction={} intensity={} ambient={}\n",
        fmt_vec(scene.light.direction),
        fmt_num(scene.light.intensity),
        fmt_num(scene.light.ambient),
    ));
    for (name, color) in &scene.materials {
        out.push_str(&format!(
            "    material {} base-color={}\n",
            quote(name),
            fmt_color(*color)
        ));
    }
    for node in &scene.roots {
        write_node(&mut out, node, 1);
    }
    out.push_str("}\n");
    out
}

fn write_node(out: &mut String, node: &Node, depth: usize) {
    let indent = "    ".repeat(depth);
    let keyword = match node.geometry {
        Geometry::Group => "node",
        Geometry::Cube => "cube",
        Geometry::Sphere { .. } => "sphere",
        Geometry::Plane => "plane",
        Geometry::MeshRef(_) => "mesh",
    };
    let mut line = format!("{indent}{keyword}");
    if let Some(name) = &node.name {
        line.push_str(&format!(" {}", quote(name)));
    }
    if let Geometry::Sphere { rings, segments } = node.geometry {
        line.push_str(&format!(" rings={rings} segments={segments}"));
    }
    if let Geometry::MeshRef(src) = &node.geometry {
        line.push_str(&format!(" src={}", quote(src)));
    }
    let t = &node.transform;
    if t.translate != Vec3::ZERO {
        line.push_str(&format!(" translate={}", fmt_vec(t.translate)));
    }
    if t.rotate_deg != Vec3::ZERO {
        line.push_str(&format!(" rotate={}", fmt_vec(t.rotate_deg)));
    }
    if t.scale != Vec3::new(1.0, 1.0, 1.0) {
        line.push_str(&format!(" scale={}", fmt_vec(t.scale)));
    }
    if let Some(m) = &node.material {
        line.push_str(&format!(" material={}", quote(m)));
    }
    if node.children.is_empty() {
        out.push_str(&line);
        out.push('\n');
    } else {
        out.push_str(&format!("{line} {{\n"));
        for child in &node.children {
            write_node(out, child, depth + 1);
        }
        out.push_str(&format!("{indent}}}\n"));
    }
}

fn fmt_num(n: f32) -> String {
    // Rust's shortest float formatting round-trips through `parse::<f32>()`.
    format!("{n}")
}

fn fmt_vec(v: Vec3) -> String {
    format!("({} {} {})", fmt_num(v.x), fmt_num(v.y), fmt_num(v.z))
}

fn fmt_color(c: Rgb) -> String {
    let unit = |x: u8| fmt_num(f32::from(x) / 255.0);
    format!("({} {} {})", unit(c.r), unit(c.g), unit(c.b))
}

fn quote(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

// ---------------------------------------------------------------------------
// Builder: raw nodes → Scene
// ---------------------------------------------------------------------------

fn build_scene(mut nodes: Vec<RawNode>) -> Result<Scene, DslError> {
    // Optional single `scene { ... }` wrapper.
    if nodes.len() == 1 && nodes[0].name == "scene" {
        let wrapper = nodes.pop().unwrap();
        nodes = wrapper.children;
    }

    let mut scene = Scene::default();
    for node in nodes {
        match node.name.as_str() {
            "material" => {
                let name = label(&node)?;
                let color = prop_color(&node, "base-color")?.unwrap_or(Rgb::new(210, 210, 210));
                scene.materials.push((name, color));
            }
            "background" => {
                let color = prop_color(&node, "color")?
                    .or(node.args.first().and_then(as_color))
                    .ok_or_else(|| DslError {
                        line: node.line,
                        message: "background needs a color, e.g. background color=(0.1 0.1 0.1)"
                            .into(),
                    })?;
                scene.background = color;
            }
            "camera" => {
                scene.camera = Some(SceneCamera {
                    position: prop_vec(&node, "position")?.unwrap_or(Vec3::new(3.0, 2.2, 4.5)),
                    look_at: prop_vec(&node, "look-at")?.unwrap_or(Vec3::ZERO),
                    fov_deg: prop_num(&node, "fov")?.unwrap_or(50.0),
                });
            }
            "light" => {
                let mut light = SceneLight::default();
                if let Some(d) = prop_vec(&node, "direction")? {
                    light.direction = d;
                }
                if let Some(i) = prop_num(&node, "intensity")? {
                    light.intensity = i;
                }
                if let Some(a) = prop_num(&node, "ambient")? {
                    light.ambient = a;
                }
                scene.light = light;
            }
            "node" | "cube" | "box" | "sphere" | "plane" | "mesh" => {
                scene.roots.push(build_node(node)?);
            }
            other => return err(node.line, format!("unknown scene element '{other}'")),
        }
    }
    Ok(scene)
}

fn build_node(raw: RawNode) -> Result<Node, DslError> {
    let geometry = match raw.name.as_str() {
        "node" => Geometry::Group,
        "cube" | "box" => Geometry::Cube,
        "plane" => Geometry::Plane,
        "sphere" => Geometry::Sphere {
            rings: prop_num(&raw, "rings")?.map(|n| n as u32).unwrap_or(12),
            segments: prop_num(&raw, "segments")?.map(|n| n as u32).unwrap_or(24),
        },
        "mesh" => {
            // The first positional string is the label/name; the asset path must
            // be given explicitly as `src="…"` (research 03 sketch).
            let src = prop_str(&raw, "src").ok_or_else(|| DslError {
                line: raw.line,
                message: "mesh needs src=\"path.obj\"".into(),
            })?;
            Geometry::MeshRef(src)
        }
        other => return err(raw.line, format!("'{other}' cannot be a node")),
    };

    let transform = Transform {
        translate: prop_vec(&raw, "translate")?.unwrap_or(Vec3::ZERO),
        rotate_deg: prop_vec(&raw, "rotate")?.unwrap_or(Vec3::ZERO),
        scale: prop_scale(&raw)?,
    };

    let name = raw.args.iter().find_map(as_str);
    let material = prop_str(&raw, "material");
    let children = raw
        .children
        .into_iter()
        .map(build_node)
        .collect::<Result<Vec<_>, _>>()?;

    Ok(Node {
        name,
        transform,
        geometry,
        material,
        children,
    })
}

// --- property accessors -----------------------------------------------------

fn find<'a>(node: &'a RawNode, key: &str) -> Option<&'a Value> {
    node.props.iter().find(|(k, _)| k == key).map(|(_, v)| v)
}

fn label(node: &RawNode) -> Result<String, DslError> {
    node.args.iter().find_map(as_str).ok_or_else(|| DslError {
        line: node.line,
        message: format!("{} needs a name, e.g. {} \"name\"", node.name, node.name),
    })
}

fn prop_num(node: &RawNode, key: &str) -> Result<Option<f32>, DslError> {
    match find(node, key) {
        Some(Value::Num(n)) => Ok(Some(*n)),
        Some(_) => err(node.line, format!("{key} must be a number")),
        None => Ok(None),
    }
}

fn prop_vec(node: &RawNode, key: &str) -> Result<Option<Vec3>, DslError> {
    match find(node, key) {
        Some(Value::Vec3(v)) => Ok(Some(Vec3::new(v[0], v[1], v[2]))),
        Some(_) => err(
            node.line,
            format!("{key} must be a vector like ({key}=(x y z))"),
        ),
        None => Ok(None),
    }
}

fn prop_color(node: &RawNode, key: &str) -> Result<Option<Rgb>, DslError> {
    match find(node, key) {
        Some(Value::Vec3(v)) => Ok(Some(rgb_from_unit(*v))),
        Some(_) => err(
            node.line,
            format!("{key} must be a color like ({key}=(r g b))"),
        ),
        None => Ok(None),
    }
}

/// `scale` accepts a uniform number or a vector.
fn prop_scale(node: &RawNode) -> Result<Vec3, DslError> {
    match find(node, "scale") {
        Some(Value::Num(n)) => Ok(Vec3::new(*n, *n, *n)),
        Some(Value::Vec3(v)) => Ok(Vec3::new(v[0], v[1], v[2])),
        Some(_) => err(node.line, "scale must be a number or (x y z)"),
        None => Ok(Vec3::new(1.0, 1.0, 1.0)),
    }
}

fn prop_str(node: &RawNode, key: &str) -> Option<String> {
    match find(node, key) {
        Some(Value::Str(s)) => Some(s.clone()),
        _ => None,
    }
}

fn as_str(v: &Value) -> Option<String> {
    match v {
        Value::Str(s) => Some(s.clone()),
        _ => None,
    }
}

fn as_color(v: &Value) -> Option<Rgb> {
    match v {
        Value::Vec3(c) => Some(rgb_from_unit(*c)),
        _ => None,
    }
}

fn rgb_from_unit(c: [f32; 3]) -> Rgb {
    let ch = |x: f32| (x.clamp(0.0, 1.0) * 255.0 + 0.5) as u8;
    Rgb::new(ch(c[0]), ch(c[1]), ch(c[2]))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fr4_1_parses_primitives_and_transforms() {
        let scene =
            parse("scene {\n  sphere \"ball\" translate=(0 1 0) scale=2\n  plane scale=(8 1 8)\n}")
                .unwrap();
        assert_eq!(scene.roots.len(), 2);
        assert_eq!(scene.roots[0].name.as_deref(), Some("ball"));
        assert_eq!(
            scene.roots[0].geometry,
            Geometry::Sphere {
                rings: 12,
                segments: 24
            }
        );
        assert_eq!(scene.roots[0].transform.scale, Vec3::new(2.0, 2.0, 2.0));
        assert_eq!(scene.roots[1].geometry, Geometry::Plane);
    }

    #[test]
    fn fr4_1_works_without_scene_wrapper() {
        let scene = parse("cube\nsphere").unwrap();
        assert_eq!(scene.roots.len(), 2);
    }

    #[test]
    fn fr4_1_comments_are_ignored() {
        let scene = parse("// a scene\ncube /* inline */ translate=(1 0 0) // trailing\n").unwrap();
        assert_eq!(scene.roots.len(), 1);
        assert_eq!(scene.roots[0].transform.translate, Vec3::new(1.0, 0.0, 0.0));
    }

    #[test]
    fn fr4_3_named_materials_and_references() {
        let scene = parse("material \"red\" base-color=(1 0 0)\ncube material=red").unwrap();
        assert_eq!(scene.materials.len(), 1);
        assert_eq!(scene.roots[0].material.as_deref(), Some("red"));
        assert_eq!(
            scene.resolve_material(Some("red")).base_color,
            Rgb::new(255, 0, 0)
        );
    }

    #[test]
    fn fr4_3_camera_and_light_props() {
        let scene = parse(
            "camera position=(1 2 3) look-at=(0 0 0) fov=60\nlight direction=(0 -1 0) intensity=2 ambient=0.3",
        )
        .unwrap();
        let cam = scene.camera.unwrap();
        assert_eq!(cam.position, Vec3::new(1.0, 2.0, 3.0));
        assert_eq!(cam.fov_deg, 60.0);
        assert_eq!(scene.light.intensity, 2.0);
        assert_eq!(scene.light.ambient, 0.3);
    }

    #[test]
    fn fr4_1_nested_nodes_build_a_tree() {
        let scene = parse("node \"g\" translate=(0 1 0) {\n  cube\n  sphere\n}").unwrap();
        assert_eq!(scene.roots.len(), 1);
        assert_eq!(scene.roots[0].children.len(), 2);
    }

    #[test]
    fn fr4_1_errors_carry_line_numbers() {
        let e = parse("cube\nsphere material=\n").unwrap_err();
        assert_eq!(e.line, 2);
    }

    #[test]
    fn fr4_3_unknown_element_is_an_error() {
        let e = parse("teapot").unwrap_err();
        assert!(
            e.message.contains("unknown scene element"),
            "got: {}",
            e.message
        );
    }

    #[test]
    fn fr4_1_mesh_requires_src() {
        assert!(parse("mesh \"m\"").is_err());
        assert!(parse("mesh src=\"a.obj\"").is_ok());
    }

    #[test]
    fn fr4_7_round_trip_through_serialize_and_parse() {
        let src = "scene {\n  \
            material \"red\" base-color=(0.8 0.1 0.1)\n  \
            camera position=(3 2 5) look-at=(0 1 0) fov=55\n  \
            light direction=(-1 -2 -1) intensity=1.5 ambient=0.2\n  \
            node \"group\" translate=(0 1 0) {\n    \
                sphere rings=8 segments=16 material=red\n    \
                cube translate=(2 0 0) rotate=(0 45 0) scale=(1 2 1)\n  \
            }\n  \
            mesh src=\"teapot.obj\" scale=0.5\n\
        }";
        let scene = parse(src).unwrap();
        let reparsed = parse(&serialize(&scene)).unwrap();
        assert_eq!(scene, reparsed, "serialize→parse must reproduce the scene");
    }
}
